apiVersion: v1
kind: Service
metadata:
  name: transaction-db
spec:
  selector:
    app: transaction-db
  ports:
    - port: {{ .Values.postgresql.port }}
      targetPort: {{ .Values.postgresql.port }}
