apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-ingestor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transaction-ingestor
  template:
    metadata:
      labels:
        app: transaction-ingestor
    spec:
      containers:
        - name: transaction-ingestor
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          env:
            - name: DB_HOST
              value: {{ .Values.env.db.host }}
            - name: DB_PORT
              value: {{ .Values.env.db.port }}
            - name: DB_NAME
              value: {{ .Values.env.db.name }}
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: transaction-ingestor-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: transaction-ingestor-secret
                  key: DB_PASSWORD
