{{- $svcName := printf "%s" .Release.Name }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  {{- if eq .Values.mode "canary" }}
  annotations:
    nginx.ingress.kubernetes.io/canary: "true"
    nginx.ingress.kubernetes.io/canary-weight: "{{ .Values.ingress.canaryWeight }}"
  {{- end }}
spec:
  ingressClassName: nginx
  rules:
  - host: transaction-ingestor.com
    http:
      paths:
      - path: /transaction
        pathType: Prefix
        backend:
          service:
            name: {{ $svcName }}
            port:
              number: 80
