apiVersion: v1
kind: Service
metadata:
  name: transaction-ingestor
spec:
  selector:
    app: transaction-ingestor
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
