apiVersion: v1
kind: Service
metadata:
  name: transaction-viewer
spec:
  selector:
    app: transaction-viewer
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
